## NumPy

In [1]:
import numpy as np

In [2]:
liste = [1,2,3]

In [3]:
liste

[1, 2, 3]

In [4]:
np.array(liste)

array([1, 2, 3])

In [5]:
type(liste)

list

In [6]:
type(np.array(liste))

numpy.ndarray

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
np.array([[1,2,3],[4,6,9],[11,2,4]])

array([[ 1,  2,  3],
       [ 4,  6,  9],
       [11,  2,  4]])

In [11]:
# arange
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [12]:
# zeros ve ones
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# linspace
np.linspace(0,1000,30)

array([   0.        ,   34.48275862,   68.96551724,  103.44827586,
        137.93103448,  172.4137931 ,  206.89655172,  241.37931034,
        275.86206897,  310.34482759,  344.82758621,  379.31034483,
        413.79310345,  448.27586207,  482.75862069,  517.24137931,
        551.72413793,  586.20689655,  620.68965517,  655.17241379,
        689.65517241,  724.13793103,  758.62068966,  793.10344828,
        827.5862069 ,  862.06896552,  896.55172414,  931.03448276,
        965.51724138, 1000.        ])

In [18]:
# eye
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random

In [19]:
# rand
np.random.rand(10)

array([0.0620465 , 0.58129348, 0.99896954, 0.21703916, 0.74159817,
       0.72433653, 0.0106714 , 0.27953631, 0.67529248, 0.80289724])

In [20]:
np.random.rand(5,5)

array([[0.19947163, 0.43884054, 0.01154886, 0.22532988, 0.10128473],
       [0.49191065, 0.15703379, 0.0322361 , 0.92928204, 0.74524375],
       [0.04259465, 0.98198744, 0.56243051, 0.70509615, 0.38343068],
       [0.95003589, 0.10915397, 0.66950444, 0.07646156, 0.5465905 ],
       [0.48643952, 0.64393377, 0.55902817, 0.7105062 , 0.19367824]])

In [22]:
# randn
np.random.randn(10)

array([ 0.26350136, -0.67612507,  0.87079867,  0.63025667,  0.38771453,
        0.1398651 , -0.57514784,  0.00784947,  1.23153126,  0.90489605])

In [35]:
# randint
np.random.seed(123)
np.random.randint(1,100)

67

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.shape

(25,)

In [39]:
# reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.max()

24

In [41]:
arr.min()

0

In [42]:
arr.dtype

dtype('int32')

In [44]:
arr[3:5]

array([3, 4])

In [46]:
arr[0:5]=10

In [47]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr_2 = arr[10:14]

In [49]:
arr_2

array([10, 11, 12, 13])

In [50]:
arr_2

array([10, 11, 12, 13])

In [51]:
arr_3 = arr_2 # yeni atama

In [52]:
arr_3

array([10, 11, 12, 13])

In [53]:
arr_3 =np.array([0,1,2,3,4])

In [54]:
arr_3

array([0, 1, 2, 3, 4])

In [55]:
arr_2

array([10, 11, 12, 13])

In [56]:
arr_2d = np.array(([1,2,30],[20,12,12],[10,20,20]))

In [57]:
arr_2d

array([[ 1,  2, 30],
       [20, 12, 12],
       [10, 20, 20]])

In [58]:
arr_2d[1]

array([20, 12, 12])

In [59]:
arr_2d[1,1]

12

In [60]:
arr_2d[1:,1:]

array([[12, 12],
       [20, 20]])

In [61]:
arr = np.arange(1,100)

In [62]:
arr > 50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [63]:
arr[arr>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [64]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [69]:
arr_2 = np.arange(101,200)

In [70]:
arr_2

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199])

In [71]:
arr + arr_2

array([102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204,
       206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230,
       232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256,
       258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282,
       284, 286, 288, 290, 292, 294, 296, 298])

In [72]:
arr * arr_2

array([  101,   204,   309,   416,   525,   636,   749,   864,   981,
        1100,  1221,  1344,  1469,  1596,  1725,  1856,  1989,  2124,
        2261,  2400,  2541,  2684,  2829,  2976,  3125,  3276,  3429,
        3584,  3741,  3900,  4061,  4224,  4389,  4556,  4725,  4896,
        5069,  5244,  5421,  5600,  5781,  5964,  6149,  6336,  6525,
        6716,  6909,  7104,  7301,  7500,  7701,  7904,  8109,  8316,
        8525,  8736,  8949,  9164,  9381,  9600,  9821, 10044, 10269,
       10496, 10725, 10956, 11189, 11424, 11661, 11900, 12141, 12384,
       12629, 12876, 13125, 13376, 13629, 13884, 14141, 14400, 14661,
       14924, 15189, 15456, 15725, 15996, 16269, 16544, 16821, 17100,
       17381, 17664, 17949, 18236, 18525, 18816, 19109, 19404, 19701])

In [73]:
arr ** 2

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801],
      dtype=int32)

In [74]:
liste_1=[1,2,3,4,6]
liste_2=[3,5,1,3,5]

In [77]:
type(arr)

numpy.ndarray

In [78]:
type(liste_1)

list

In [81]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
       5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
       6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532,
       6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
       6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781,
       7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
       7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669,
       7.81024968, 7.87400787, 7.93725393, 8.        , 8.06225775,
       8.1240384 , 8.18535277, 8.24621125, 8.30662386, 8.36660027,
       8.42614977, 8.48528137, 8.54400375, 8.60232527, 8.66025

In [82]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16, 2.35385267e+17,
       6.39843494e+17, 1.73927494e+18, 4.72783947e+18, 1.28516001e+19,
       3.49342711e+19, 9.49611942e+19, 2.58131289e+20, 7.01673591e+20,
       1.90734657e+21, 5.18470553e+21, 1.40934908e+22, 3.83100800e+22,
       1.04137594e+23, 2.83075330e+23, 7.69478527e+23, 2.09165950e+24,
      

In [84]:
arr = np.arange(0,10)

In [85]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [89]:
a = np.random.rand(100)

In [90]:
print(a)

[0.22685145 0.55131477 0.71946897 0.42310646 0.9807642  0.68482974
 0.4809319  0.39211752 0.34317802 0.72904971 0.43857224 0.0596779
 0.39804426 0.73799541 0.18249173 0.17545176 0.53155137 0.53182759
 0.63440096 0.84943179 0.72445532 0.61102351 0.72244338 0.32295891
 0.36178866 0.22826323 0.29371405 0.63097612 0.09210494 0.43370117
 0.43086276 0.4936851  0.42583029 0.31226122 0.42635131 0.89338916
 0.94416002 0.50183668 0.62395295 0.1156184  0.31728548 0.41482621
 0.86630916 0.25045537 0.48303426 0.98555979 0.51948512 0.61289453
 0.12062867 0.8263408  0.60306013 0.54506801 0.34276383 0.30412079
 0.41702221 0.68130077 0.87545684 0.51042234 0.66931378 0.58593655
 0.6249035  0.67468905 0.84234244 0.08319499 0.76368284 0.24366637
 0.19422296 0.57245696 0.09571252 0.88532683 0.62724897 0.72341636
 0.01612921 0.59443188 0.55678519 0.15895964 0.15307052 0.69552953
 0.31876643 0.6919703  0.55438325 0.38895057 0.92513249 0.84167
 0.35739757 0.04359146 0.30476807 0.39818568 0.70495883 0.99535848

In [91]:
a.max()

0.9953584820340174

In [92]:
a.argmax()

89

In [93]:
a[89]

0.9953584820340174

In [94]:
np.log(a)

array([-1.48345987, -0.59544936, -0.32924188, -0.86013145, -0.01942322,
       -0.37858503, -0.7320296 , -0.93619369, -1.06950597, -0.31601336,
       -0.82423073, -2.81879357, -0.92119209, -0.30381768, -1.70105042,
       -1.74039117, -0.63195543, -0.63143593, -0.4550741 , -0.16318763,
       -0.32233518, -0.49261984, -0.32511623, -1.13023017, -1.01669506,
       -1.47725579, -1.22514862, -0.46048726, -2.3848267 , -0.83539952,
       -0.84196565, -0.70585742, -0.85371439, -1.16391519, -0.85249161,
       -0.112733  , -0.05745962, -0.68948056, -0.47168031, -2.15746021,
       -1.14795334, -0.87989561, -0.14351344, -1.38447456, -0.72766769,
       -0.01454549, -0.65491711, -0.48956242, -2.11503833, -0.190748  ,
       -0.50573837, -0.60684471, -1.0707136 , -1.19033032, -0.87461579,
       -0.38375142, -0.13300942, -0.67251678, -0.4015023 , -0.53454377,
       -0.47015804, -0.39350336, -0.17156865, -2.48656817, -0.26960271,
       -1.41195531, -1.6387485 , -0.55781773, -2.3464062 , -0.12

In [95]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [97]:
np.five(10)

AttributeError: module 'numpy' has no attribute 'five'

In [98]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [110]:
A = np.arange(9).reshape(3,3)

In [107]:
liste = np.random.randn(10000)

In [108]:
liste.std()

1.0000912240981894

In [109]:
liste.mean()

0.020036582647665557

In [111]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
A.sum(axis=0)

array([ 9, 12, 15])

In [114]:
A.sum(axis=1)

array([ 3, 12, 21])